  - name: Disable default redis module
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis:7
    ansible.builtin.command: dnf module enable redis:7 -y
  
  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present
  
  - name: allow remote connection #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no
  
  - name: start and enable redis #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes