- name: Disable default nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx:1.24
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: start and enable nginx.service  #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download the frontend code #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
  ansible.builtin.get_url: 
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

# this module thinks files exist on ansible control server, needs to extract on remote machine
#remote_src: yes means file already exist in frontend server
- name: extract frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent
    
- name: copy roboshop nginx conf  #http://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    remote_src: no
    notify:
      - Restart nginx
