- name: app setup
  include_role:
    name: common
    tasks_from: app-setup
    
- name: app setup
  include_role:
    name: common
    tasks_from: nodejs

- name: copy mongodb repo #http://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.abhi84s-daws.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.abhi84s-daws.site </app/db/master-data.js
  when: catalogue_output.stdout | int < 0 #for this search in brower like ansible convert string to int

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml