  - name: create roboshop system user #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Download the {{ component }} code" #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
    ansible.builtin.get_url: 
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
      dest: /tmp/{{ component }}.zip

  # this module thinks files exist on ansible control server, needs to extract on remote machine
  #remote_src: yes means file already exist in {{ component }} server
  - name: extract {{ component }} code
    ansible.builtin.unarchive:
      src: "/tmp/{{ component }}.zip"
      dest: /app
      remote_src: yes