- name: copy catalogue service to system directory #http://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue.service  #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
  ansible.builtin.service:
    name: catalogue
    state: restarted #even app is not running we can restart
    enabled: yes